=== lexwebb/Fabric/Fabric.Core/DebugResources/Schemas/workflow.json
{
    "$id": "http://example.com/example.json",
    "type": "object",
    "definitions": {},
    "$schema": "http://json-schema.org/draft-06/schema#",
    "properties": {
        "name": {
            "$id": "/properties/name",
            "type": "string",
            "title": "The Name Schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "Test"
            ]
        },
        "description": {
            "$id": "/properties/description",
            "type": "string",
            "title": "The Description Schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "A workflow"
            ]
        },
        "vertical": {
            "$id": "/properties/vertical",
            "type": "string",
            "title": "The Vertical Schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "handset"
            ]
        },
        "stages": {
            "$id": "/properties/stages",
            "type": "array",
            "items": {
                "$id": "/properties/stages/items",
                "type": "object",
                "properties": {
                    "name": {
                        "$id": "/properties/stages/items/properties/name",
                        "type": "string",
                        "title": "The Name Schema",
                        "description": "An explanation about the purpose of this instance.",
                        "default": "",
                        "examples": [
                            "Stage 1"
                        ]
                    },
                    "order": {
                        "$id": "/properties/stages/items/properties/order",
                        "type": "integer",
                        "title": "The Order Schema",
                        "description": "An explanation about the purpose of this instance.",
                        "default": 0,
                        "examples": [
                            1
                        ]
                    },
                    "type": {
                        "$id": "/properties/stages/items/properties/type",
                        "type": "string",
                        "title": "The Type Schema",
                        "description": "An explanation about the purpose of this instance.",
                        "default": "",
                        "examples": [
                            "DFL"
                        ],
                        "enum": [
                            "DFL",
                            "SQL",
                            "CMD"
                        ]
                    },
                    "steps": {
                        "$id": "/properties/stages/items/properties/steps",
                        "type": "array",
                        "items": {
                            "$id": "/properties/stages/items/properties/steps/items",
                            "type": "object",
                            "properties": {
                                "name": {
                                    "$id": "/properties/stages/items/properties/steps/items/properties/name",
                                    "type": "string",
                                    "title": "The Name Schema",
                                    "description": "An explanation about the purpose of this instance.",
                                    "default": "",
                                    "examples": [
                                        "Stage 1"
                                    ]
                                },
                                "order": {
                                    "$id": "/properties/stages/items/properties/steps/items/properties/order",
                                    "type": "integer",
                                    "title": "The Order Schema",
                                    "description": "An explanation about the purpose of this instance.",
                                    "default": 0,
                                    "examples": [
                                        1
                                    ]
                                },
                                "code": {
                                    "$id": "/properties/stages/items/properties/steps/items/properties/code",
                                    "type": "string",
                                    "title": "The Code Schema",
                                    "description": "An explanation about the purpose of this instance.",
                                    "default": "",
                                    "examples": [
                                        "SELECT * FROM X"
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "required": [
        "name"
    ]
}

=== lexwebb/Fabric/Fabric.Core/DebugResources/Pages/workflow1.json
{
  "name": "Test",
  "description": "A workflow",
  "vertical": "handset",
  "stages": [
    {
      "name": "Stage 1",
      "order": 1,
      "type": "DFL",
      "steps": [
        {
          "name": "Stage 1",
          "order": 1,
          "code": "SELECT * FROM X"
        },
        {
          "name": "Stage 2",
          "order": 2,
          "code": "SELECT * FROM X"
        },
        {
          "name": "Stage 3",
          "order": 3,
          "code": "SELECT * FROM X"
        }
      ]
    },
    {
      "name": "Stage 2",
      "order": 2,
      "type": "DFL",
      "steps": [
        {
          "name": "Stage 1",
          "order": 1,
          "code": "SELECT * FROM X"
        },
        {
          "name": "Stage 2",
          "order": 2,
          "code": "SELECT * FROM X"
        }
      ]
    }
  ]
}
